package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var (
	packageRe = regexp.MustCompile(`(?m)^package\s+(\w+)`)
	pageVarRe = regexp.MustCompile(`(?m)^var\s+Page\s*=`)
	compVarRe = regexp.MustCompile(`(?m)^var\s+Component\s*=`)
	moduleRe  = regexp.MustCompile(`(?m)^module\s+(\S+)`)
)

// cmdGen regenerates the generated files by hand; dev and build do it
// automatically.
func cmdGen(args []string) error {
	appDir, cfg, err := findApp()
	if err != nil {
		return err
	}
	if err := writeRegistry(appDir); err != nil {
		return err
	}
	return writeIcons(appDir, cfg)
}

// writeIcons generates gantry_icons.go, embedding the app's default
// icon files (from the gantry.json "icons" directory) and registering
// them with the runtime. No icons directory = no file.
func writeIcons(appDir string, cfg appConfig) error {
	genPath := filepath.Join(appDir, "gantry_icons.go")
	dir := cfg.Icons
	if dir == "" {
		dir = "icons"
	}
	png := filepath.Join(dir, "icon.png")
	ico := filepath.Join(dir, "icon.ico")
	hasPNG := fileExists(filepath.Join(appDir, png))
	hasICO := fileExists(filepath.Join(appDir, ico))
	if !hasPNG && !hasICO {
		// Stale generated file after the icons were removed: drop it.
		if fileExists(genPath) {
			data, err := os.ReadFile(genPath)
			if err == nil && strings.Contains(string(data), "Code generated by gantry") {
				_ = os.Remove(genPath)
			}
		}
		return nil
	}

	var b strings.Builder
	b.WriteString("// Code generated by gantry gen; DO NOT EDIT.\n")
	b.WriteString("// Embeds the app's default icons (gantry.json \"icons\" directory).\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("import (\n\t_ \"embed\"\n\n\t\"github.com/B-Commissions/Gantry/gantry\"\n)\n\n")
	if hasPNG {
		fmt.Fprintf(&b, "//go:embed %q\nvar gantryDefaultIconPNG []byte\n\n", filepath.ToSlash(png))
	} else {
		b.WriteString("var gantryDefaultIconPNG []byte\n\n")
	}
	if hasICO {
		fmt.Fprintf(&b, "//go:embed %q\nvar gantryDefaultIconICO []byte\n\n", filepath.ToSlash(ico))
	} else {
		b.WriteString("var gantryDefaultIconICO []byte\n\n")
	}
	b.WriteString("func init() {\n\tgantry.SetDefaultIcons(gantryDefaultIconPNG, gantryDefaultIconICO)\n}\n")
	return os.WriteFile(genPath, []byte(b.String()), 0o644)
}

func fileExists(p string) bool {
	st, err := os.Stat(p)
	return err == nil && !st.IsDir()
}

type registryEntry struct {
	alias      string
	importPath string
	varName    string // "Page" or "Component"
}

// writeRegistry scans pages/, components/ and layouts/ for Go halves
// exporting the conventional Page/Component vars and generates
// gantry_registry.go, so main.go never lists pairs by hand:
//
//	app := ui.NewApp(gantryPairs()...)
func writeRegistry(appDir string) error {
	modData, err := os.ReadFile(filepath.Join(appDir, "go.mod"))
	if err != nil {
		return fmt.Errorf("reading go.mod: %w", err)
	}
	m := moduleRe.FindSubmatch(modData)
	if m == nil {
		return fmt.Errorf("no module line in go.mod")
	}
	module := strings.Trim(string(m[1]), `"`)

	var entries []registryEntry
	for _, kind := range []string{"pages", "components", "layouts"} {
		dir := filepath.Join(appDir, kind)
		items, err := os.ReadDir(dir)
		if err != nil {
			continue // the kind's folder is optional
		}
		names := make([]string, 0, len(items))
		for _, it := range items {
			if it.IsDir() {
				names = append(names, it.Name())
			}
		}
		sort.Strings(names)
		for _, name := range names {
			varName, ok := scanPair(filepath.Join(dir, name))
			if !ok {
				continue // tsx-only pair: nothing to register
			}
			entries = append(entries, registryEntry{
				alias:      kind[:1] + "_" + sanitizeIdent(name),
				importPath: module + "/" + kind + "/" + name,
				varName:    varName,
			})
		}
	}

	var b strings.Builder
	b.WriteString("// Code generated by gantry gen; DO NOT EDIT.\n")
	b.WriteString("// Regenerated by gantry dev/build/gen from the pages/, components/\n")
	b.WriteString("// and layouts/ folders - add a pair and it registers itself.\n\n")
	b.WriteString("package main\n\n")
	if len(entries) > 0 {
		b.WriteString("import (\n")
		for _, e := range entries {
			fmt.Fprintf(&b, "\t%s %q\n", e.alias, e.importPath)
		}
		b.WriteString(")\n\n")
	}
	b.WriteString("// gantryPairs returns every registered Page and Component.\n")
	b.WriteString("func gantryPairs() []any {\n")
	if len(entries) == 0 {
		b.WriteString("\treturn nil\n")
	} else {
		b.WriteString("\treturn []any{\n")
		for _, e := range entries {
			fmt.Fprintf(&b, "\t\t%s.%s,\n", e.alias, e.varName)
		}
		b.WriteString("\t}\n")
	}
	b.WriteString("}\n")
	return os.WriteFile(filepath.Join(appDir, "gantry_registry.go"), []byte(b.String()), 0o644)
}

// scanPair looks at every .go file in a pair folder for the exported
// registration var. Returns which one it found.
func scanPair(dir string) (varName string, ok bool) {
	items, err := os.ReadDir(dir)
	if err != nil {
		return "", false
	}
	for _, it := range items {
		if it.IsDir() || !strings.HasSuffix(it.Name(), ".go") || strings.HasSuffix(it.Name(), "_test.go") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, it.Name()))
		if err != nil {
			continue
		}
		if pageVarRe.Match(data) {
			return "Page", true
		}
		if compVarRe.Match(data) {
			return "Component", true
		}
	}
	return "", false
}

func sanitizeIdent(s string) string {
	out := make([]rune, 0, len(s))
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			out = append(out, r)
		default:
			out = append(out, '_')
		}
	}
	return string(out)
}
