package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var (
	packageRe = regexp.MustCompile(`(?m)^package\s+(\w+)`)
	pageVarRe = regexp.MustCompile(`(?m)^var\s+Page\s*=`)
	compVarRe = regexp.MustCompile(`(?m)^var\s+Component\s*=`)
	moduleRe  = regexp.MustCompile(`(?m)^module\s+(\S+)`)
)

// cmdGen regenerates the generated files by hand; dev and build do it
// automatically.
func cmdGen(args []string) error {
	appDir, cfg, err := findApp()
	if err != nil {
		return err
	}
	if err := writeRegistry(appDir); err != nil {
		return err
	}
	if err := writeWidgetRegistry(appDir, cfg); err != nil {
		return err
	}
	if err := writeIcons(appDir, cfg); err != nil {
		return err
	}
	if err := validateArgSpecs(cfg); err != nil {
		return fmt.Errorf("gantry.json: %w", err)
	}
	return writeArgsRegistry(appDir, cfg)
}

// writeArgsRegistry generates gantry_args.go, baking the gantry.json
// "args" spec into the binary so a production exe can resolve its args
// from environment variables (env > declared default). No args = no
// file.
func writeArgsRegistry(appDir string, cfg appConfig) error {
	genPath := filepath.Join(appDir, "gantry_args.go")
	if len(cfg.Args) == 0 {
		// Stale generated file after the args were removed: drop it.
		if fileExists(genPath) {
			data, err := os.ReadFile(genPath)
			if err == nil && strings.Contains(string(data), "Code generated by gantry") {
				_ = os.Remove(genPath)
			}
		}
		return nil
	}

	var b strings.Builder
	b.WriteString("// Code generated by gantry gen; DO NOT EDIT.\n")
	b.WriteString("// Bakes gantry.json's \"args\" spec into the binary so gantry.Arg*\n")
	b.WriteString("// resolve from environment variables in any launch, not just gantry dev.\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("import \"github.com/B-Commissions/Gantry/gantry\"\n\n")
	b.WriteString("func init() {\n\tgantry.SetArgSpecs([]gantry.ArgSpec{\n")
	for _, name := range sortedArgNames(cfg) {
		spec := cfg.Args[name]
		typ := spec.Type
		if typ == "" {
			typ = "string"
		}
		def, _, err := argDefault(spec)
		if err != nil {
			return fmt.Errorf("gantry.json: args.%s: %w", name, err)
		}
		var defLit string
		switch v := def.(type) {
		case bool:
			defLit = fmt.Sprintf("%t", v)
		case int:
			defLit = fmt.Sprintf("%d", v)
		default:
			defLit = fmt.Sprintf("%q", v)
		}
		fmt.Fprintf(&b, "\t\t{Name: %q, Type: %q, Env: %q, Description: %q, Default: %s},\n",
			name, typ, argEnvName(name, spec), spec.Description, defLit)
	}
	b.WriteString("\t})\n}\n")
	return os.WriteFile(genPath, []byte(b.String()), 0o644)
}

// writeIcons generates gantry_icons.go, embedding the app's default
// icon files (from the gantry.json "icons" directory) and registering
// them with the runtime. No icons directory = no file.
func writeIcons(appDir string, cfg appConfig) error {
	genPath := filepath.Join(appDir, "gantry_icons.go")
	dir := cfg.Icons
	if dir == "" {
		dir = "icons"
	}
	png := filepath.Join(dir, "icon.png")
	ico := filepath.Join(dir, "icon.ico")
	hasPNG := fileExists(filepath.Join(appDir, png))
	hasICO := fileExists(filepath.Join(appDir, ico))
	if !hasPNG && !hasICO {
		// Stale generated file after the icons were removed: drop it.
		if fileExists(genPath) {
			data, err := os.ReadFile(genPath)
			if err == nil && strings.Contains(string(data), "Code generated by gantry") {
				_ = os.Remove(genPath)
			}
		}
		return nil
	}

	var b strings.Builder
	b.WriteString("// Code generated by gantry gen; DO NOT EDIT.\n")
	b.WriteString("// Embeds the app's default icons (gantry.json \"icons\" directory).\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("import (\n\t_ \"embed\"\n\n\t\"github.com/B-Commissions/Gantry/gantry\"\n)\n\n")
	if hasPNG {
		fmt.Fprintf(&b, "//go:embed %q\nvar gantryDefaultIconPNG []byte\n\n", filepath.ToSlash(png))
	} else {
		b.WriteString("var gantryDefaultIconPNG []byte\n\n")
	}
	if hasICO {
		fmt.Fprintf(&b, "//go:embed %q\nvar gantryDefaultIconICO []byte\n\n", filepath.ToSlash(ico))
	} else {
		b.WriteString("var gantryDefaultIconICO []byte\n\n")
	}
	b.WriteString("func init() {\n\tgantry.SetDefaultIcons(gantryDefaultIconPNG, gantryDefaultIconICO)\n}\n")
	return os.WriteFile(genPath, []byte(b.String()), 0o644)
}

func fileExists(p string) bool {
	st, err := os.Stat(p)
	return err == nil && !st.IsDir()
}

type registryEntry struct {
	alias      string
	importPath string
	varName    string // "Page" or "Component"
}

// writeRegistry scans pages/, components/ and layouts/ for Go halves
// exporting the conventional Page/Component vars and generates
// gantry_registry.go, so main.go never lists pairs by hand:
//
//	app := ui.NewApp(gantryPairs()...)
func writeRegistry(appDir string) error {
	module, err := moduleName(appDir)
	if err != nil {
		return err
	}

	// Pairs nest to any depth (pages/account/settings/settings.go):
	// walk every directory whose leaf holds a registration var.
	var entries []registryEntry
	for _, kind := range []string{"pages", "components", "layouts"} {
		root := filepath.Join(appDir, kind)
		_ = filepath.WalkDir(root, func(p string, d os.DirEntry, err error) error {
			if err != nil || !d.IsDir() || p == root {
				return nil // the kind's folder itself is optional
			}
			varName, ok := scanPair(p)
			if !ok {
				return nil // tsx-only pair (or plain folder): nothing to register
			}
			rel, err := filepath.Rel(root, p)
			if err != nil {
				return nil
			}
			rel = filepath.ToSlash(rel)
			entries = append(entries, registryEntry{
				alias:      kind[:1] + "_" + sanitizeIdent(rel),
				importPath: module + "/" + kind + "/" + rel,
				varName:    varName,
			})
			return nil
		})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].importPath < entries[j].importPath })

	var b strings.Builder
	b.WriteString("// Code generated by gantry gen; DO NOT EDIT.\n")
	b.WriteString("// Regenerated by gantry dev/build/gen from the pages/, components/\n")
	b.WriteString("// and layouts/ folders - add a pair and it registers itself.\n\n")
	b.WriteString("package main\n\n")
	if len(entries) > 0 {
		b.WriteString("import (\n")
		for _, e := range entries {
			fmt.Fprintf(&b, "\t%s %q\n", e.alias, e.importPath)
		}
		b.WriteString(")\n\n")
	}
	b.WriteString("// gantryPairs returns every registered Page and Component.\n")
	b.WriteString("func gantryPairs() []any {\n")
	if len(entries) == 0 {
		b.WriteString("\treturn nil\n")
	} else {
		b.WriteString("\treturn []any{\n")
		for _, e := range entries {
			fmt.Fprintf(&b, "\t\t%s.%s,\n", e.alias, e.varName)
		}
		b.WriteString("\t}\n")
	}
	b.WriteString("}\n")
	return os.WriteFile(filepath.Join(appDir, "gantry_registry.go"), []byte(b.String()), 0o644)
}

// moduleName reads the app's module path from go.mod.
func moduleName(appDir string) (string, error) {
	modData, err := os.ReadFile(filepath.Join(appDir, "go.mod"))
	if err != nil {
		return "", fmt.Errorf("reading go.mod: %w", err)
	}
	m := moduleRe.FindSubmatch(modData)
	if m == nil {
		return "", fmt.Errorf("no module line in go.mod")
	}
	return strings.Trim(string(m[1]), `"`), nil
}

// scanPair looks at every .go file in a pair folder for the exported
// registration var. Returns which one it found.
func scanPair(dir string) (varName string, ok bool) {
	items, err := os.ReadDir(dir)
	if err != nil {
		return "", false
	}
	for _, it := range items {
		if it.IsDir() || !strings.HasSuffix(it.Name(), ".go") || strings.HasSuffix(it.Name(), "_test.go") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, it.Name()))
		if err != nil {
			continue
		}
		if pageVarRe.Match(data) {
			return "Page", true
		}
		if compVarRe.Match(data) {
			return "Component", true
		}
	}
	return "", false
}

func sanitizeIdent(s string) string {
	out := make([]rune, 0, len(s))
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			out = append(out, r)
		default:
			out = append(out, '_')
		}
	}
	return string(out)
}
