package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var (
	widgetVarRe  = regexp.MustCompile(`(?m)^var\s+Widget\s*=`)
	widgetNameRe = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)
)

// collectWidgets merges the widgets/ directory with gantry.json's
// mobile.widgets entries into the app's effective widget list:
// a gantry.json entry without a Go pair is a build error, a Go pair
// without an entry gets defaults. Entries come back sorted by name
// with every default filled in.
func collectWidgets(appDir string, cfg appConfig) ([]mobileWidget, error) {
	pairs := map[string]bool{}
	root := filepath.Join(appDir, "widgets")
	if entries, err := os.ReadDir(root); err == nil {
		for _, e := range entries {
			if e.IsDir() && widgetPairExists(filepath.Join(root, e.Name())) {
				pairs[e.Name()] = true
			}
		}
	}

	byName := map[string]mobileWidget{}
	if cfg.Mobile != nil {
		for _, w := range cfg.Mobile.Widgets {
			if !pairs[w.Name] {
				return nil, fmt.Errorf("gantry.json widget %q has no paired widgets/%s/%s.go exporting var Widget", w.Name, w.Name, w.Name)
			}
			byName[w.Name] = w
		}
	}
	for name := range pairs {
		if _, ok := byName[name]; !ok {
			byName[name] = mobileWidget{Name: name}
		}
	}

	widgets := make([]mobileWidget, 0, len(byName))
	for _, w := range byName {
		if !widgetNameRe.MatchString(w.Name) {
			return nil, fmt.Errorf("widget name %q must match %s (it becomes a Kotlin class and Android resource name)", w.Name, widgetNameRe)
		}
		if w.Label == "" {
			w.Label = title(w.Name)
		}
		if w.MinSize == "" {
			w.MinSize = "2x1"
		}
		if w.Resize == "" {
			w.Resize = "horizontal|vertical"
		}
		if w.RefreshMinutes == 0 {
			w.RefreshMinutes = 30
		}
		// Android floors periodic background work at 15 minutes.
		if w.RefreshMinutes < 15 {
			w.RefreshMinutes = 15
		}
		widgets = append(widgets, w)
	}
	sort.Slice(widgets, func(i, j int) bool { return widgets[i].Name < widgets[j].Name })
	return widgets, nil
}

// widgetPairExists reports whether a widget dir holds a Go file
// exporting the conventional Widget var.
func widgetPairExists(dir string) bool {
	items, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, it := range items {
		if it.IsDir() || !strings.HasSuffix(it.Name(), ".go") || strings.HasSuffix(it.Name(), "_test.go") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, it.Name()))
		if err != nil {
			continue
		}
		if widgetVarRe.Match(data) {
			return true
		}
	}
	return false
}

// writeWidgetRegistry scans widgets/ and generates gantry_widgets.go,
// init()-registering every widget with the runtime so main.go never
// lists them - the widget sibling of writeRegistry. No widgets = no
// file (a stale generated one is removed).
func writeWidgetRegistry(appDir string, cfg appConfig) error {
	genPath := filepath.Join(appDir, "gantry_widgets.go")
	widgets, err := collectWidgets(appDir, cfg)
	if err != nil {
		return err
	}
	if len(widgets) == 0 {
		if fileExists(genPath) {
			data, err := os.ReadFile(genPath)
			if err == nil && strings.Contains(string(data), "Code generated by gantry") {
				_ = os.Remove(genPath)
			}
		}
		return nil
	}

	module, err := moduleName(appDir)
	if err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString("// Code generated by gantry gen; DO NOT EDIT.\n")
	b.WriteString("// Regenerated by gantry dev/build/gen from the widgets/ folder - add\n")
	b.WriteString("// a widgets/<name>/<name>.go pair and it registers itself.\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"github.com/B-Commissions/Gantry/gantry\"\n\n")
	for _, w := range widgets {
		fmt.Fprintf(&b, "\tw_%s %q\n", sanitizeIdent(w.Name), module+"/widgets/"+w.Name)
	}
	b.WriteString(")\n\n")
	b.WriteString("func init() {\n\tgantry.RegisterWidgets(\n")
	for _, w := range widgets {
		fmt.Fprintf(&b, "\t\tw_%s.Widget,\n", sanitizeIdent(w.Name))
	}
	b.WriteString("\t)\n}\n")
	return os.WriteFile(genPath, []byte(b.String()), 0o644)
}
