// Code generated by gantry gen; DO NOT EDIT.
// Embeds the app's default icons (gantry.json "icons" directory).

package main

import (
	_ "embed"

	"github.com/B-Commissions/Gantry/gantry"
)

//go:embed "icons/icon.png"
var gantryDefaultIconPNG []byte

//go:embed "icons/icon.ico"
var gantryDefaultIconICO []byte

func init() {
	gantry.SetDefaultIcons(gantryDefaultIconPNG, gantryDefaultIconICO)
}
