// Code generated by gantry gen; DO NOT EDIT.
// Regenerated by gantry dev/build/gen from the pages/, components/
// and layouts/ folders - add a pair and it registers itself.

package main

import (
	p_index "hello/pages/index"
)

// gantryPairs returns every registered Page and Component.
func gantryPairs() []any {
	return []any{
		p_index.Page,
	}
}
