// Code generated by gantry gen; DO NOT EDIT.
// Regenerated by gantry dev/build/gen from the widgets/ folder - add
// a widgets/<name>/<name>.go pair and it registers itself.

package main

import (
	"github.com/B-Commissions/Gantry/gantry"

	w_status "demo/widgets/status"
)

func init() {
	gantry.RegisterWidgets(
		w_status.Widget,
	)
}
