// Code generated by gantry gen; DO NOT EDIT.
// Embeds the app's resources/ directory (images, fonts, json, ...)
// so gantry.Resource/Resources and the /resources/ route can serve it.

package main

import (
	"embed"
	"io/fs"

	"github.com/B-Commissions/Gantry/gantry"
)

//go:embed all:resources
var gantryResourcesDir embed.FS

func init() {
	sub, err := fs.Sub(gantryResourcesDir, "resources")
	if err != nil {
		panic(err)
	}
	gantry.SetResources(sub)
}
