// Code generated by gantry gen; DO NOT EDIT.
// Regenerated by gantry dev/build/gen from the pages/, components/
// and layouts/ folders - add a pair and it registers itself.

package main

import (
	c_example "demo/components/example"
	p_account_profile "demo/pages/account/profile"
	p_debug "demo/pages/debug"
	p_index "demo/pages/index"
	p_settings "demo/pages/settings"
)

// gantryPairs returns every registered Page and Component.
func gantryPairs() []any {
	return []any{
		c_example.Component,
		p_account_profile.Page,
		p_debug.Page,
		p_index.Page,
		p_settings.Page,
	}
}
