// Code generated by gantry gen; DO NOT EDIT.
// Bakes gantry.json's "args" spec into the binary so gantry.Arg*
// resolve from environment variables in any launch, not just gantry dev.

package main

import "github.com/BlueBeard63/Gantry/gantry"

func init() {
	gantry.SetArgSpecs([]gantry.ArgSpec{
		{Name: "api-host", Type: "string", Env: "GANTRY_ARG_API_HOST", Description: "backend host the app talks to", Default: "localhost"},
		{Name: "mock-data", Type: "bool", Env: "GANTRY_ARG_MOCK_DATA", Description: "serve fake data instead of the real backend", Default: false},
	})
}
