// Code generated by gantry gen; DO NOT EDIT.
// Regenerated by gantry dev/build/gen from the pages/, components/
// and layouts/ folders - add a pair and it registers itself.

package main

import (
	p_index "demo/pages/index"
	p_settings "demo/pages/settings"
	c_example "demo/components/example"
)

// gantryPairs returns every registered Page and Component.
func gantryPairs() []any {
	return []any{
		p_index.Page,
		p_settings.Page,
		c_example.Component,
	}
}
